-- Stores the final rendition selected by a volunteer.
-- Browser roles have no direct access; the Edge Function writes with service_role.
create table if not exists public.selected_audio_renditions (
  id bigint generated by default as identity primary key,
  author text not null,
  title text not null,
  content_format text not null,
  language_code text not null,
  model text not null,
  speaker text not null,
  narration_text text not null,
  audio_base64 text not null,
  mime_type text not null default 'audio/mpeg',
  sarvam_request_id text,
  created_by text not null default 'Volunteer',
  created_at timestamptz not null default now()
);

alter table public.selected_audio_renditions
  add column if not exists created_by text not null default 'Volunteer';

alter table public.selected_audio_renditions enable row level security;
revoke all on table public.selected_audio_renditions from public, anon, authenticated;
create index if not exists selected_audio_renditions_created_at_idx
  on public.selected_audio_renditions (created_at desc);
